### ISSUE TITLE
Addition of an option to make videos with length of audio in the coub

### ISSUE THREAD

**Issue by MasterPetrik** [TeeSeal/coub-dl#12]
The current version of the program have a loop video option, and time length option.
And also by default, it makes output video with a length of the video file from coub.

But if you want to make output video with a length of audio from coub, in the current state it's not so easy:
1.) download mp3 separately
2.) find it in the output folder and check it's length
3.) download coub, but before it, you should calculate loops number, then set loops count, and then also set time, which you have got from mp3 before
4.) and only then you will get a proper result

So there is a suggestion to make a parameter to make output video looped to coub music length.

And also  `--time` parameter will not work if you previously will not use `--loop` parameter before it, with loop time > time set manually. 
Maybe it's would be better to make `--time` parameter work independently from `--loop` parameter?

**Comment by TeeSeal** [comment]
`--time` only works to limit the video length. As in if the output video length would be longer than the amount of seconds specified with `--time`, then it shrinks it down. It does not work the other way.

Currently, in order to achieve what you want here you simply pass a really big number to `--loop`. As in `coub-dl -i https://coub.com/view/10fs8d --loop 999`. Even though the video looped 999 times would be super long, at the end, the script compares the audio and the video and trims it down to the shorter length. i.e. if the audio is shorter than the video, then the output length will be exactly the audio length.

**Comment by MasterPetrik** [comment]
> Currently, in order to achieve what you want here you simply pass a really big number to `--loop`. As in `coub-dl -i https://coub.com/view/10fs8d --loop 999`. Even though the video looped 999 times would be super long, at the end, the script compares the audio and the video and trims it down to the shorter length. i.e. if the audio is shorter than the video, then the output length will be exactly the audio length.

Thanks for the explanation, indeed it will solve this problem. The only thing that I may ask you now, is put this info in readme and help, since it's a very important feature. Then the issue will be completely solved. Thanks.

**Comment by TeeSeal** [comment]
@MasterPetrik I've updated the readme with the info you requested. I'm not going to make another release for this, however. This info is going to be available only on the GitHub readme for now.

Also sorry for the delay. I had some stuff going on IRL.
