### ISSUE TITLE
Audio track not recognised

### ISSUE THREAD

**Issue by dreerr** [TeeSeal/coub-dl#2]
Under OS X High Sierra (ffmpeg 3.4.2, coub-dl 1.4.1) the audio track is not recognised by any major player. Only VLC is able to read and play it. Any ideas?

**Comment by TeeSeal** [comment]
Oh my.. You're right. I only tested with IINA. I will look into it, thanks for the report.

**Comment by TeeSeal** [comment]
@dreerr I've managed to solve this issue. Turns out it's something with the encoding of the sound that coub offers. I shipped a fix in the latest 1.4.2 version.

**tl;dr**: sound should work fine now but overall process will be slower. If you want speed but potentially broken sound use the `-C` option.

Here's the longer version from the readme:

---

**NOTE:** About the `-C` option. Originally codecs were copied by default as it improved the speed of the process, but it was reported that some players fail to detect the sound of the output file when doing so, as such, the codec copying is now an option.

* If you DO use the `-C` option:
  some players will have issues with the sound of the output BUT the process will be faster!
  Use this if you don't really care about sound, or your player (or whatever else uses your output) supports the codecs for sound.

* If you DON'T use the `-C` option:
  all players will be able to play your file just fine, but the process will take longer as ffmpeg will have to decode and reencode your file.

The `--copy-codec` option will only work if you don't use any other video filters such as `crop` and `scale`.
If you do, adding this option will have no effect. (FFmpeg will still have to decode and encode the video)
