### ISSUE TITLE
Changing file format syntax suggestion 

### ISSUE THREAD

**Issue by MasterPetrik** [TeeSeal/coub-dl#8]
Considering suggestions in #5 and #7 issues, I have a last suggestion, that you may don't like, but it will coincide with implementing these ones.
There are can be problems with default way of naming output files in part of .ext:

There is a way to make it clear and workable - to turn ext marks into additional commands:
like `-mp4` `-mp3` `-gif`  and don't mention ext in output path field. Syntax examples:

input without output: 
`coub-dl -i https://coub.com/someid -mp4`  >>> `default_folder\coubname.mp4`
input with custom output: 
`coub-dl -i https://coub.com/someid -o C:\coubs -gif` >>> `C:\coubs\coubname.gif`
input with custom name: 
`coub-dl -i https://coub.com/someid -o C:\coubs\newname -mp3` >> `C:\coubs\newname.mp3`

Make ext parameter required for working of program(as for -i parameter) and don't start a process until ext will be set. 

I know, this way seems less comfortable, but instead, it will solve default output format problem and make output format selection more reliable and clear.  
Because in current state you can't see a list of supported formats, nor on github page, nor in coub-dl internal help. About supporting gif saving you learn only from one of code examples. 
As commands, they will be more intuitive, and also they will make a list of supported formats right into the help file. And if you, for example, would like to add webm format output support, you could just add `-webm` command to the list and work with it. 

But if you don't like this idea, I will understand.

**Comment by TeeSeal** [comment]
I was thinking the same thing. The main issue with this is that it still doesn't completely avoid ambiguity. See, for example if you do:

```sh
$ coub-dl -i https://coub.com/someid -o C:\coubs -gif
```

I can't easily tell whether you want `C:\coubs.gif` or `C:\coubs\coubname.gif`. The only way for me to differentiate between these is to explicitly check if the path that I got exists and is a directory. If it is a directory then I go the `C:\coubs\coubname.gif`, otherwise `C:\coubs.gif`.  But then again, what if you wanted the output to be `C:\coubs.gif` even though the `C:\coubs` directory exists?

I'm thinking a better solution would be if there was some special pattern (`<name>`?) in the path that I would replace with the coub name. 

i.e.
`coub-dl -i https://coub.com/someid -o C:\coubs\<name>.mp4` => `C:\coubs\coubname.mp4`

And I could still support defaults, but only for the current directory:
Let current directory be `C:\coubs\stuff`

`coub-dl -i https://coub.com/someid` => `C:\coubs\stuff\coubname.mp4`
`coub-dl -i https://coub.com/someid -f gif` => `C:\coubs\stuff\coubname.gif`

Let me know what you think.

**Comment by TeeSeal** [comment]
Also, I'm not really sure about listing all the supported formats. I'm using FFmpeg for conversion, whatever FFmpeg supports, coub-dl also does.

**Comment by MasterPetrik** [comment]
> I can't easily tell whether you want C:\coubs.gif or C:\coubs\coubname.gif. 

True. I didn't think about it, but it's a problem indeed .

> I'm thinking a better solution would be if there was some special pattern (<name>?) in the path that I would replace with the coub name.

> Also, I'm not really sure about listing all the supported formats. I'm using FFmpeg for conversion, whatever FFmpeg supports, coub-dl also does.

If supported formats list is equal to FFmpeg supported formarts list, then separate commands for each format seems worse than current implementation, considering also that FFmpeg can add/remove it's supported formats in the future, make this list static was a really bad idea. 
But I still think that mentioning current aviable formats in readme or on github page would be helpful.
Pattern <name> implimentation seems like the easiest way to make all clear and simple. I'm fully support that, it will solve the naming problem for sure.
